anitama:
  url: https://app.anitama.net/rss/google
  xpath: //div[@id="area-content-article"]
  pic: default

pixivision:
  url: http://www.pixivision.net/zh/rss
  xpath: //a[div/img[@class="am__work__illust " or @class="aie__illust "]]
  pic: google

hacg:
  url: http://www.hacg.wiki/wp/feed
  xpath: //div[@class="entry-content"]
  pic: default

bombdance:
  url: http://feeds.feedburner.com/bombdance
  xpath: //div[@class="post-body entry-content"]
  pic: default

sfoxstudio:
  url: http://feeds.feedburner.com/sfoxstudio
  xpath: //div[@class="entry-inner"]/*[position()<last()-2]
  pic: default

maniahero:
  url: http://www.maniahero.com/?feed=rss2
  xpath: //div[@class="entry-content"]
  pic: default

gamerboom:
  url: http://gamerboom.com/feed
  xpath: //div[@class="cnt_body"]
  pic: default

youxiputao:
  url: http://youxiputao.com/feed
  xpath: //div[@class="info"]
  pic: default

youxichaguan:
  url: http://www.youxichaguan.com/rss.php
  xpath: //div[@class="arc-article-detail"]
  pic: default

gamasutra:
  url: http://feeds.feedburner.com/GamasutraFeatureArticles/
  xpath: //div[@class="item_body mobile_image_transform"]
  pic: default

kotaku:
  url: http://feeds.gawker.com/kotaku/full
  xpath: //div[@class="post-content entry-content js_entry-content "]
  pic: default

glixel:
  url: http://www.glixel.com/rss
  xpath: //div[@class="article-content"]
  pic: default

wizards:
  url: http://magic.wizards.com/en/rss/rss.xml?tags=Making%20Magic
  xpath: //div[@id="content-detail-page-of-an-article"]
  pic: default

jasondan:
  url: http://feed.cnblogs.com/blog/u/91938/rss
  xpath: //div[@id="cnblogs_post_body"]
  pic: default

jiqizhixin:
  url: http://www.jiqizhixin.com/rss
  xpath: //div[@class="al-article-content"]
  pic: default

qianduan:
  url: https://www.qianduan.net/rss
  xpath: //section[@class="post-content"]
  pic: default

leavesongs:
  url: https://www.leavesongs.com/feed
  xpath: //div[@class="content"]
  pic: default

yinwang:
  url: http://feed43.com/6385828222086215.xml
  xpath: //div[h2]
  pic: default

9to5mac:
  url: https://9to5mac.com/feed
  xpath: //div[@class="post-body"]
  pic: default

idownloadblog:
  url: http://www.idownloadblog.com/feed
  xpath: //div[@class="entry"]
  pic: default

typeisbeautiful:
  url: http://feeds.feedburner.com/typeisbeautiful
  xpath: //div[@class="entry-content"]
  pic: default

guancha:
  url: http://rss.guancha.cn/All.html
  xpath: //div[@class="content all-txt"]
  pic: default

vice:
  url: http://www.vice.cn/index/rss/
  xpath: //div[@class="article-content"]
  pic: default

bbc:
  url: http://feeds.bbci.co.uk/zhongwen/simp/rss.xml
  xpath: //div[@property="articleBody"]
  pic: default

nytimes:
  url: https://cn.nytimes.com/rss.html
  xpath: //div[@id="content"]
  pic: default
